name: CI

on:
  push:

jobs:
  build:
    name: Build and Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build and Test
        run: |
          xcodebuild build test -scheme "Obire" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify && exit ${PIPESTATUS[0]}
